source 'https://github.com/CocoaPods/Specs.git'

target 'JHActivityButton', :exclusive => true do
  pod "JHActivityButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JHActivityButton", :path => "../"

  
end
